#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Jun 02, 2021 09:30:07 AM PDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top39 {base} {
    global vTcl
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightbackground #f5deb3 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 717x232+332+225
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Most Available Widgets"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab51 \
        -foreground black -text {Bandpass Filter} \
        -background $vTcl(actual_gui_bg) -height 266 \
        -highlightbackground #f5deb3 -highlightcolor black -width 330 
    vTcl:DefineAlias "$top.lab51" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab51
    entry $site_3_0.ent52 \
        -background white -disabledforeground #b8a786 \
        -font {-family {DejaVu Sans Mono} -size 10} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f5deb3 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent52" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #b8a786 \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f5deb3 \
        -highlightcolor black -text {High Fraction Cutoff} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent46 \
        -background white -disabledforeground #b8a786 \
        -font {-family {DejaVu Sans Mono} -size 10} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f5deb3 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #b8a786 \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f5deb3 \
        -highlightcolor black -text {High Fraction Cutoff} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label6_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor center -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Generate 
    vTcl:DefineAlias "$site_3_0.but57" "Generate2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.ent52 \
        -in $site_3_0 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 0 -relx 0.045 -y 0 -rely 0.537 -width 144 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.045 -y 0 -rely 0.39 -width 0 \
        -relwidth 0.536 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but57 \
        -in $site_3_0 -x 0 -relx 0.124 -y 0 -rely 0.829 -width 177 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab48 \
        -foreground black -text {Manual Filter} \
        -background $vTcl(actual_gui_bg) -height 266 \
        -highlightbackground #f5deb3 -highlightcolor black -width 340 
    vTcl:DefineAlias "$top.lab48" "Labelframe3_1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab48
    entry $site_3_0.ent52 \
        -background white -disabledforeground #b8a786 \
        -font {-family {DejaVu Sans Mono} -size 10} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f5deb3 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent52" "Entry1_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #b8a786 \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f5deb3 \
        -highlightcolor black -text {High Cutoff (Hz)} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label6_2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent46 \
        -background white -disabledforeground #b8a786 \
        -font {-family {DejaVu Sans Mono} -size 10} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f5deb3 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry1_1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #b8a786 \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f5deb3 \
        -highlightcolor black -text {Low Cutoff (Hz)} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label6_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor center -background $vTcl(actual_gui_bg) \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Generate 
    vTcl:DefineAlias "$site_3_0.but56" "Generate1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.ent52 \
        -in $site_3_0 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 0 -relx 0.045 -y 0 -rely 0.537 -width 144 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.045 -y 0 -rely 0.39 -width 0 \
        -relwidth 0.536 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 0 -relx 0.12 -y 0 -rely 0.829 -width 187 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab55 \
        -foreground black -text {Raw Data} -background $vTcl(actual_gui_bg) \
        -height 265 -highlightbackground #f5deb3 -highlightcolor black \
        -width 289 
    vTcl:DefineAlias "$top.lab55" "Labelframe3_2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab55
    button $site_3_0.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Open file} 
    vTcl:DefineAlias "$site_3_0.but58" "Open" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Raw Signal} 
    vTcl:DefineAlias "$site_3_0.but59" "Open_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Fourier Transfom} 
    vTcl:DefineAlias "$site_3_0.but60" "Open_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but58 \
        -in $site_3_0 -x 40 -y 40 -width 127 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but59 \
        -in $site_3_0 -x 40 -y 90 -width 127 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but60 \
        -in $site_3_0 -x 40 -y 140 -width 127 -height 24 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab51 \
        -in $top -x 219 -y 8 -width 241 -relwidth 0 -height 217 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 460 -y 8 -width 249 -relwidth 0 -height 217 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 8 -y 8 -width 211 -relwidth 0 -height 216 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

